version: "3.9"
services:

  # main dispatcher api
  dispatcher:
    build: ./dispatcher_engine
    volumes:
      - asset_storage:/usr/src/app/volume
      - ./dispatcher_engine:/usr/src/app
    environment:
      - BOT_ADMIN=${BOT_ADMIN}
      - IS_DOCKER=true
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy


  # telegram bot
  telegram_bot:
    build: ./bot_engine
    volumes:
      - asset_storage:/usr/src/app/volume
      - ./bot_engine:/usr/src/app/
    expose:
      - "9001"
    environment:
      - BOT_ADMIN=${BOT_ADMIN}
      - BOT_TOKEN=${BOT_TOKEN}
      - IS_DOCKER=true
    depends_on:
      - dispatcher

  # db
  db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes:
    #   - pg_data:/var/lib/postgresql/data
    
  # screenshots
  screenshoter:
    build: ./screenshot_engine
    volumes:
      - asset_storage:/usr/src/app/volume
      - ./screenshot_engine:/usr/src/app
    hostname: screenshoter
    environment:
      - IS_DOCKER=true
    expose:
      - "9002"
    # ports:
    #   - "9002:9002"

  

  # video_gfx
  video_gfx:
    build: ./video_gfx
    volumes:
      - asset_storage:/usr/src/app/volume
      # # dev only
      - ./video_gfx:/usr/src/app
    expose:
      - "9004"
    # ports:
    #   - "9004:9004"
  
  


  video_gfx_server:
    build: ./video_gfx_server
    # environment:
    #   - IS_DOCKER=true
    volumes:
      - asset_storage:/usr/src/app/volume
    expose:
      - "9006"
    # ports:
    #   - "9006:9006"

  # sender engine
  sender:
    build: ./sender_engine
    volumes:
      - asset_storage:/usr/src/app/volume
      # # dev only
      # - ./sender_engine:/usr/src/app
    environment:
      - IS_DOCKER=true
      - BOT_ADMIN=${BOT_ADMIN}
      - BOT_TOKEN=${BOT_TOKEN}
    expose:
      - "9007"
    # ports:
    #   - "9007:9007"

  video_gfx_selenium:
    # image: "selenium/standalone-chrome"
    image: "seleniarm/standalone-chromium"
    hostname: video_gfx_selenium
    privileged: true
    shm_size: 3g
    # ports:
    #   - "4444:4444"

  screenshot_selenium:
    # image: "selenium/standalone-chrome"
    image: "seleniarm/standalone-chromium"
    hostname: screenshot_selenium
    privileged: true
    shm_size: 3g
    # ports:
    #   - "4444:4444"


volumes:
  asset_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/dev/volume/asset_storage'

  pg_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/dev/volume/pg_data/data'