FROM --platform=linux/amd64 ubuntu:latest

RUN apt update
RUN apt upgrade

# requirements
RUN apt install -y ffmpeg
RUN apt install -y git
RUN apt install -y python3
RUN apt install -y python3-pip

# create a folder
WORKDIR /usr/src/app
RUN git clone https://github.com/chemradio/cta-gfx-telegram-bot.git .
RUN git switch pre-docker
RUN pip install -r requirements.txt
COPY config_and_db /usr/src/app/config_and_db/

# install google chrome
RUN apt install -y wget
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

# # install chromedriver
# RUN apt-get install -yqq unzip
# RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
# RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/


# # install chrome
# RUN apt install -y wget
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# RUN apt install -y ./google-chrome-stable_current_amd64.deb

# RUN apt-get update && \
#     apt-get -qq -y install  libxpm4 libxrender1 libgtk2.0-0 libnss3\ 
#        libgconf-2-4  libpango1.0-0 libxss1 libxtst6 fonts-liberation\ 
#        libappindicator1 xdg-utils

# RUN apt-get -y install \
#                xvfb gtk2-engines-pixbuf \
#                xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable \
#                imagemagick x11-apps zip

               
# set display port to avoid crash
ENV DISPLAY=:99



# CMD python3 app.py
