version: "3.9"
services:
  screenshot_worker:
    # for amd64 architecture
    image: "selenium/standalone-chrome"

    # for ARM architecture
    # image: "seleniarm/standalone-chromium"

    hostname: screenshot_worker
    privileged: true
    shm_size: 4g
  video_worker:
    # for amd64 architecture
    image: "selenium/standalone-chrome"

    # for ARM architecture
    # image: "seleniarm/standalone-chromium"
    hostname: video_worker
    privileged: true
    shm_size: 4g
    depends_on:
      - screenshot_worker
  main:
    build: .
    hostname: html_server
    ports:
      - "9000:9000"
      # - "5900:5900"
      # - "7900:7900"
    depends_on: 
      - video_worker