version: '3.9'

services:
  db:
    env_file: .env
    hostname: db
    image: postgres:15-alpine
  dispatcher:
    build: ./dispatcher_engine
    depends_on:
    - db
    env_file: .env
    hostname: dispatcher
    image: chemradio/gfx-helper:dispatcher
    ports:
    - 9000:9000
    volumes:
    # - asset_storage:/usr/src/app/volume
    - ./dispatcher_engine:/usr/src/app
  front_svelte:
    build: ./front_svelte
    depends_on:
    - dispatcher
    env_file: .env
    hostname: front_svelte
    image: chemradio/gfx-helper:front_svelte
    ports:
    - 9009:9009
    volumes:
    # - asset_storage:/usr/src/app/volume
    - ./front_svelte:/usr/src/app
  screenshot_selenium:
    depends_on:
    - dispatcher
    env_file: .env
    hostname: screenshot_selenium
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 4g
  screenshoter:
    build: ./screenshot_engine
    depends_on:
    - dispatcher
    env_file: .env
    hostname: screenshoter
    image: chemradio/gfx-helper:screenshoter
    volumes:
    # - asset_storage:/usr/src/app/volume
    - ./screenshot_engine:/usr/src/app
  telegram_bot:
    build: ./bot_engine
    depends_on:
    - dispatcher
    env_file: .env
    hostname: telegram_bot
    image: chemradio/gfx-helper:telegram_bot
    volumes:
    # - asset_storage:/usr/src/app/volume
    - ./bot_engine:/usr/src/app
  telegram_sender:
    build: ./sender_engine
    depends_on:
    - dispatcher
    env_file: .env
    hostname: sender
    image: chemradio/gfx-helper:telegram_sender
    volumes:
    # - asset_storage:/usr/src/app/volume
    - ./sender_engine:/usr/src/app
  video_gfx:
    build: ./video_gfx
    depends_on:
    - dispatcher
    env_file: .env
    hostname: video_gfx
    image: chemradio/gfx-helper:video_gfx
    volumes:
    # - asset_storage:/usr/src/app/volume
    - ./video_gfx:/usr/src/app
  video_gfx_selenium:
    depends_on:
    - dispatcher
    env_file: .env
    hostname: video_gfx_selenium
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 4g
  # video_gfx_server:
  #   build: ./video_gfx_server
  #   depends_on:
  #   - dispatcher
  #   env_file: .env
  #   hostname: video_gfx_server
  #   image: chemradio/gfx-helper:video_gfx_server
  #   volumes:
  #   # - asset_storage:/usr/src/app/volume
  #   - ./video_gfx_server:/usr/src/app
  storage_unit:
    build: ./storage_unit
    depends_on:
    - dispatcher
    env_file: .env
    hostname: storage_unit
    image: chemradio/gfx-helper:storage_unit
    volumes:
    # - asset_storage:/usr/src/app/volume
    - ./storage_unit:/usr/src/app

# volumes:
#   asset_storage:
#     driver: local
#     driver_opts:
#       device: $PWD/dev/volume/asset_storage
#       o: bind
#       type: none

