version: "3.9"
services:

  # main dispatcher api
  dispatcher:
    build: 
      context: ./dispatcher_engine
      args:
        - REBUILD_DB=true
    image: chemradiogfxhelper.azurecr.io/dispatcher
    # volumes:
    #   - asset_storage:/usr/src/app/volume
    #   - ./dispatcher_engine:/usr/src/app
    env_file:
      - .env
    expose:
      - "9000"
    # ports:
    #   - "9000:9000"
    depends_on:
      db:
        condition: service_healthy

  # svelte frontend
  front_svelte:
    build: ./front_svelte
    image: chemradiogfxhelper.azurecr.io/front_svelte
    # volumes:
    #   - asset_storage:/usr/src/app/volume
    #   - ./front_svelte:/usr/src/app/
    expose:
      - "9009"
    ports:
      - "80:9009"
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
    depends_on:
      - dispatcher

#   # telegram bot
#   telegram_bot:
#     build: ./bot_engine
#     image: chemradiogfxhelper.azurecr.io/telegram_bot
#     volumes:
#       - asset_storage:/usr/src/app/volume
#       # - ./bot_engine:/usr/src/app/
#     expose:
#       - "9001"
#     env_file:
#       - .env      
#     # environment:
#     #   - BOT_ADMIN=${BOT_ADMIN}
#     #   - BOT_TOKEN=${BOT_TOKEN}
#     #   - IS_DOCKER=true
#     depends_on:
#       - dispatcher

  db:
    image: "postgres:15-alpine"
    env_file:
      - .env    
    # environment:
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes:
    #   - pg_data:/var/lib/postgresql/data

#     # screenshots
#   screenshoter:
#     build: ./screenshot_engine
#     image: chemradiogfxhelper.azurecr.io/screenshoter

#     volumes:
#       - asset_storage:/usr/src/app/volume
#       # - ./screenshot_engine:/usr/src/app
#     hostname: screenshoter
#     env_file:
#       - .env    
#     # environment:
#     #   - IS_DOCKER=true
#     expose:
#       - "9002"
#     depends_on:
#       - dispatcher

#   video_gfx:
#     build: ./video_gfx
#     image: chemradiogfxhelper.azurecr.io/video_gfx

#     volumes:
#       - asset_storage:/usr/src/app/volume
#       # - ./video_gfx:/usr/src/app
#     expose:
#       - "9004"
#     depends_on:
#       - dispatcher

#   video_gfx_server:
#     build: ./video_gfx_server
#     image: chemradiogfxhelper.azurecr.io/video_gfx_server

#     volumes:
#       - asset_storage:/usr/src/app/volume
#     expose:
#       - "9006"
#     depends_on:
#       - dispatcher

#   sender:
#     build: ./sender_engine
#     image: chemradiogfxhelper.azurecr.io/sender

#     volumes:
#       - asset_storage:/usr/src/app/volume
#       # - ./sender_engine:/usr/src/app
#     env_file:
#       - .env
#     # environment:
#     #   - IS_DOCKER=true
#     #   - BOT_ADMIN=${BOT_ADMIN}
#     #   - BOT_TOKEN=${BOT_TOKEN}
#     expose:
#       - "9007"
#     depends_on:
#       - dispatcher

#   screenshot_selenium:
#     # image: "selenium/standalone-chrome"
#     image: "seleniarm/standalone-chromium"
#     hostname: screenshot_selenium
#     privileged: true
#     shm_size: 4g
#     depends_on:
#       - dispatcher

#   video_gfx_selenium:
#     # image: "selenium/standalone-chrome"
#     image: "seleniarm/standalone-chromium"
#     hostname: video_gfx_selenium
#     privileged: true
#     shm_size: 4g
#     depends_on:
#       - dispatcher

# # volumes:
# #   asset_storage:
# #     driver: local
#     # driver_opts:
#     #   type: 'none'
#     #   o: 'bind'
#     #   device: '$PWD/dev/volume/asset_storage'
# volumes:
#   asset_storage:
#     driver: azure_file
#   # pg_data:
#   #   driver: local
#   #   driver_opts:
#   #     type: 'none'
#   #     o: 'bind'
#   #     device: '$PWD/dev/volume/pg_data/data'
