version: '3.9'

services:
  db:
    restart: always
    environment:
      IS_DOCKER: 1
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: db
    image: postgres:15-alpine
    volumes:
       - ./pg_data:/var/lib/postgresql/data
  dispatcher:
    restart: always
    build: ./dispatcher_engine
    platform: ${PLATFORM}
    depends_on:
    - db
    environment:
      IS_DOCKER: 1
      BOT_ADMIN_EMAIL: ${BOT_ADMIN_EMAIL}
      BOT_ADMIN_PASSWORD: ${BOT_ADMIN_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REGISTER_PASSPHRASE: ${REGISTER_PASSPHRASE}
    hostname: dispatcher
    ports:
      - "9000:9000"
  front-svelte:
    restart: always
    build: ./front_svelte
    platform: ${PLATFORM}
    # depends_on:
    # - dispatcher
    hostname: front_svelte
    ports:
      - "80:80"
  bot-engine:
    restart: always
    build: ./bot_engine
    platform: ${PLATFORM}
    environment:
      IS_DOCKER: 1
      BOT_ADMIN: ${BOT_ADMIN}
      BOT_TOKEN: ${BOT_TOKEN}
    # depends_on:
    # - dispatcher
    hostname: bot_engine
  screenshot-selenium:
    restart: always
    hostname: screenshot_selenium
    image: ${SELENIUM_IMAGE}
    privileged: true
    shm_size: 2g
  screenshoter:
    restart: always
    build: ./screenshot_engine
    platform: ${PLATFORM}
    environment:
      IS_DOCKER: 1
    depends_on:
    - dispatcher
    hostname: screenshoter
  storage-unit:
    restart: always
    build: ./storage_unit
    platform: ${PLATFORM}
    environment:
      IS_DOCKER: 1
    depends_on:
    - dispatcher
    hostname: storage_unit
  video-gfx:
    restart: always
    build: ./video_gfx
    platform: ${PLATFORM}
    environment:
      IS_DOCKER: 1
    depends_on:
    - dispatcher
    hostname: video_gfx
    volumes:
      - ./video_gfx:/usr/src/app
  video-gfx-selenium-1:
    restart: always
    hostname: video_gfx_selenium_one
    image: ${SELENIUM_IMAGE}
    privileged: true
    shm_size: 3g
  video-gfx-selenium-2:
    restart: always
    hostname: video_gfx_selenium_two
    image: ${SELENIUM_IMAGE}
    privileged: true
    shm_size: 3g
  video-gfx-selenium-3:
    restart: always
    hostname: video_gfx_selenium_three
    image: ${SELENIUM_IMAGE}
    privileged: true
    shm_size: 3g