version: '3.9'

services:
  db:
    env_file: .env
    hostname: db
    image: postgres:15-alpine
  dispatcher:
    build: ./dispatcher_engine
    depends_on:
    - db
    env_file: .env
    hostname: dispatcher
    image: chemradio:dispatcher
  front_svelte:
    build: ./front_svelte
    depends_on:
    - dispatcher
    env_file: .env
    hostname: front_svelte
    image: chemradio:front_svelte
    ports:
    - 80:9009
  screenshot_selenium:
    env_file: .env
    hostname: screenshot_selenium
    image: selenium/standalone-chrome
    privileged: true
    shm_size: 4g
  screenshoter:
    build: ./screenshot_engine
    depends_on:
    - dispatcher
    env_file: .env
    hostname: screenshoter
    image: chemradio:screenshoter
  storage_unit:
    build: ./storage_unit
    depends_on:
    - dispatcher
    env_file: .env
    hostname: storage_unit
    image: chemradio:storage_unit
  telegram_bot:
    build: ./bot_engine
    depends_on:
    - dispatcher
    env_file: .env
    hostname: telegram_bot
    image: chemradio:telegram_bot
  telegram_sender:
    build: ./sender_engine
    depends_on:
    - dispatcher
    env_file: .env
    hostname: sender
    image: chemradio:telegram_sender
  video_gfx:
    build: ./video_gfx
    depends_on:
    - dispatcher
    env_file: .env
    hostname: video_gfx
    image: chemradio:video_gfx
  video_gfx_selenium:
    env_file: .env
    hostname: video_gfx_selenium
    image: selenium/standalone-chrome
    privileged: true
    shm_size: 4g

volumes: {}

