version: '3.9'

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: db
    image: postgres:15-alpine
  dispatcher:
    build: ./dispatcher_engine
    depends_on:
    - db
    environment:
      BOT_ADMIN_EMAIL: ${BOT_ADMIN_EMAIL}
      BOT_ADMIN_PASSWORD: ${BOT_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REGISTER_PASSPHRASE: ${REGISTER_PASSPHRASE}
    hostname: dispatcher
    image: chemradio/cta-gfx-helper:dispatcher
  front_svelte:
    build: ./front_svelte
    depends_on:
    - dispatcher
    hostname: front_svelte
    image: chemradio/cta-gfx-helper:front_svelte
    ports:
    - 80:9009
  screenshot_selenium:
    hostname: screenshot_selenium
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 4g
  screenshoter:
    build: ./screenshot_engine
    depends_on:
    - dispatcher
    hostname: screenshoter
    image: chemradio/cta-gfx-helper:screenshoter
  storage_unit:
    build: ./storage_unit
    depends_on:
    - dispatcher
    hostname: storage_unit
    image: chemradio/cta-gfx-helper:storage_unit
  video_gfx:
    build: ./video_gfx
    depends_on:
    - dispatcher
    hostname: video_gfx
    image: chemradio/cta-gfx-helper:video_gfx
  video_gfx_selenium:
    hostname: video_gfx_selenium
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 4g

