services:
  screenshot-selenium:
    restart: unless-stopped
    hostname: screenshot_selenium
    image: seleniarm/standalone-chromium
    # build: ../seleniarm_custom/screenshot
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
  # screenshoter:
  #   restart: unless-stopped
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #   platform: linux/arm64
  #   environment:
  #     IS_DOCKER: 1
  #   hostname: screenshoter
  #   ports:
  #     - "9002:9002"
