services:
  screenshot-selenium:
    restart: unless-stopped
    hostname: screenshot_selenium
    image: seleniarm/standalone-chromium
    # build: ../seleniarm_custom/screenshot
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
