MIME_TO_EXTENSION = {
    "image/png": ["png"],
    "image/jpeg": ["jpg", "jpeg"],
    "image/webp": ["webp"],
    "image/heif": ["heif"],
    "image/heic": ["heif"],
    "image/bmp": ["bmp"],
    "image/gif": ["gif"],
    "application/pdf": ["pdf"],
    "application/msword": ["doc"],
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ["docx"],
    "audio/wav": ["wav"],
    "audio/x-wav": ["wav"],
    "audio/mpeg": ["mp3"],
    "audio/ogg": ["ogg"],
    "application/ogg": ["ogg"],
    "video/mp4": ["mp4"],
    "audio/flac": ["flac"],
    "audio/aac": ["aac"],
    "audio/alac": ["alac"],
    "audio/mp4": ["m4a"],
    "audio/x-m4a": ["m4a"],
}

EXTENSION_TO_MIME = {
    "png": ["image/png"],
    "jpg": ["image/jpeg"],
    "jpeg": ["image/jpeg"],
    "webp": ["image/webp"],
    "heif": ["image/heif", "image/heic"],
    "bmp": ["image/bmp"],
    "gif": ["image/gif"],
    "pdf": ["application/pdf"],
    "doc": ["application/msword"],
    "docx": ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    "wav": ["audio/wav", "audio/x-wav"],
    "mp3": ["audio/mpeg"],
    "ogg": ["audio/ogg", "application/ogg"],
    "mp4": ["video/mp4"],
    "flac": ["audio/flac"],
    "aac": ["audio/aac"],
    "alac": ["audio/alac"],
    "m4a": ["audio/mp4", "audio/x-m4a"],
}
