services:
  screenshot-selenium:
    restart: unless-stopped
    hostname: screenshot_selenium
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    environment:
      - SE_START_VNC="false"
      - SE_START_XVFB="false"
