import os
from pathlib import Path

DISPATCHER_NODE_HOSTNAME = "dispatcher"
DISPATCHER_NODE_PORT = 9000
DISPATCHER_NODE_URL = f"http://{DISPATCHER_NODE_HOSTNAME}:{DISPATCHER_NODE_PORT}"

LIST_ORDERS_ENDPOINT = f"{DISPATCHER_NODE_URL}/orders/list"
EDIT_ORDER_ENDPOINT = f"{DISPATCHER_NODE_URL}/orders/edit"
GET_ONE_ORDER_ENDPOINT = f"{DISPATCHER_NODE_URL}/orders/get_one"


BOT_TOKEN = os.environ.get("BOT_TOKEN")
BOT_ADMIN = os.environ.get("BOT_ADMIN")

VOLUME_MOUNTPOINT = Path.cwd() / "volume"
VIDEO_GFX_FOLDER = VOLUME_MOUNTPOINT / "video_exports"
SCREENSHOTS_FOLDER = VOLUME_MOUNTPOINT / "screenshots"
