services:
  db:
    restart: unless-stopped
    hostname: db
    image: mongo:6.0
    volumes:
      - ./mongodata:/data/db
  dispatcher:
    restart: unless-stopped
    build: ./dispatcher_engine
    volumes:
      - ./dispatcher_engine:/usr/src/app
    platform: linux/arm64
    depends_on:
    - db
    environment:
      IS_DOCKER: 1
      BOT_ADMIN_EMAIL: ${BOT_ADMIN_EMAIL}
      BOT_ADMIN_PASSWORD: ${BOT_ADMIN_PASSWORD}
      BOT_ADMIN: ${BOT_ADMIN}
      BOT_TOKEN: ${BOT_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      REGISTER_PASSPHRASE: ${REGISTER_PASSPHRASE}
    hostname: dispatcher
    # ports:
    #   - "9000:9000"
  file_converter:
    restart: unless-stopped
    build: ./file_converter
    volumes:
      - ./file_converter:/usr/src/app
    platform: linux/arm64
    environment:
      IS_DOCKER: 1
    depends_on:
    - dispatcher
    hostname: file_converter
    # ports:
    #   - "9005:9005"
  bot-engine:
    restart: unless-stopped
    build: ./bot_engine
    volumes:
      - ./bot_engine:/usr/src/app
    platform: linux/arm64
    environment:
      IS_DOCKER: 1
      BOT_ADMIN: ${BOT_ADMIN}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
    - dispatcher
    hostname: bot_engine
  screenshot-selenium:
    restart: unless-stopped
    hostname: screenshot_selenium
    build: ./seleniarm_custom/screenshot
    privileged: true
    shm_size: 2g
    environment:
      - SE_START_VNC="false"
      - SE_START_NO_VNC="false"
      - SE_START_XVFB="false"
  screenshoter:
    restart: unless-stopped
    build: ./screenshot_engine
    volumes:
      - ./screenshot_engine:/usr/src/app
    platform: linux/arm64
    environment:
      IS_DOCKER: 1
    depends_on:
    - dispatcher
    hostname: screenshoter
    # ports:
    #   - "9002:9002"
  video-gfx:
    restart: unless-stopped
    build: ./video_gfx
    platform: linux/arm64
    environment:
      IS_DOCKER: 1
      VERTICAL_RESOLUTION: ${VERTICAL_RESOLUTION}
    depends_on:
    - dispatcher
    hostname: video_gfx
    volumes:
      - ./video_gfx:/usr/src/app
    shm_size: 2g
    # ports:
    #   - "9004:9004"
      
  video-gfx-selenium-1:
    restart: unless-stopped
    hostname: video_gfx_selenium_one
    build: ./seleniarm_custom/video_gfx
    privileged: true
    shm_size: 2g
    environment:
      - SE_START_VNC="false"
      - SE_START_NO_VNC="false"
      - SE_START_XVFB="false"
  video-gfx-selenium-2:
    restart: unless-stopped
    hostname: video_gfx_selenium_two
    build: ./seleniarm_custom/video_gfx
    privileged: true
    shm_size: 2g
    environment:
      - SE_START_VNC="false"
      - SE_START_NO_VNC="false"
      - SE_START_XVFB="false"
  video-gfx-selenium-3:
    restart: unless-stopped
    hostname: video_gfx_selenium_three
    build: ./seleniarm_custom/video_gfx
    privileged: true
    shm_size: 2g
    environment:
      - SE_START_VNC="false"
      - SE_START_NO_VNC="false"
      - SE_START_XVFB="false"

    