services:
  video-gfx-selenium-1:
    restart: unless-stopped
    hostname: video_gfx_selenium_one
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 3g
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4444:4444"
  video-gfx-selenium-2:
    restart: unless-stopped
    hostname: video_gfx_selenium_two
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 3g
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4445:4444"
  video-gfx-selenium-3:
    restart: unless-stopped
    hostname: video_gfx_selenium_three
    image: seleniarm/standalone-chromium
    privileged: true
    shm_size: 3g
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4446:4444"