from io import BytesIO

from fastapi import APIRouter, HTTPException, Response, UploadFile

from utils.assets.file_convert.workers import (
    convert_audio_to_wav,
    convert_pdf_to_png,
    convert_word_to_png,
)

router = APIRouter()


@router.post(
    "/",
    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response,
)
async def convert_file(
    upload_file: UploadFile,
):
    # check file type and convert file if neccessary
    native_support_mimes = [
        "image/jpeg",
        "image/png",
        "audio/wav",
        "audio/x-wav",
        "audio/mpeg",
        "audio/mp3",
    ]

    if upload_file.content_type not in native_support_mimes:
        try:
            file_mime = upload_file.content_type
            if "audio" in file_mime:
                file_bytesio = await convert_audio_to_wav(upload_file)
                # extesion = "wav"
                media_type = "audio/wav"

            elif file_mime == "application/pdf":
                file_bytesio = await convert_pdf_to_png(upload_file)
                # extesion = "png"
                media_type = "image/png"

            elif file_mime == "application/msword":
                file_bytesio = await convert_word_to_png(upload_file)
                # extesion = "png"
                media_type = "image/png"

        except Exception as e:
            raise HTTPException(400, f"Bad file. {str(e)}")
            # raise Exception(f"Unable to convert file: {upload_file.filename}, {str(e)}")

    else:
        file_bytesio = BytesIO(upload_file.file.read())
        # extesion = get_file_extension_from_mime(upload_file.content_type)

    return Response(content=file_bytesio, media_type=media_type)

    # # store temp file for response
    # filename = generate_random_filename(extension=extesion)
    # with open(filename, "wb") as file:
    #     file.write(file_bytesio.read())

    # return FileResponse(path=Path.cwd() / filename)
    # with open(filename, "wb") as file:
    #     file.write(file_bytesio.read())

    # return FileResponse(path=Path.cwd() / filename)
